CREATE TABLE pais
(
	codigo BIGINT AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	capital VARCHAR(100) NOT NULL,
	regiao VARCHAR(255) NOT NULL,
	subregiao VARCHAR(255) NOT NULL,
	area DECIMAL(10,2) NOT NULL,
	
	PRIMARY KEY(codigo)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;